var ApiConstants = {
	VIDEO_RECEIVED: 'VIDEO_RECEIVED',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
	LIKES_RECEIVED: 'LIKES_RECEIVED',
	SESSION_RECEIVED: 'SESSION_RECEIVED',
	SESSION_DESTROYED: 'SESSION_DESTROYED',
	VIDEO_INDEX_RECEIVED: 'VIDEO_INDEX_RECEIVED',
	USER_RECEIVED: 'USER_RECEIVED',
	CURRENT_USER_LIKE_RECEIVED: 'CURRENT_USER_LIKE_RECEIVED'
};

module.exports = ApiConstants;
