var ApiConstants = {
	VIDEO_RECEIVED: 'VIDEO_RECEIVED',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
	LIKES_RECEIVED: 'LIKES_RECEIVED',
	SESSION_RECEIVED: 'SESSION_RECEIVED',
	SESSION_DESTROYED: 'SESSION_DESTROYED',
	VIDEO_INDEX_RECEIVED: 'VIDEO_INDEX_RECEIVED'
};

module.exports = ApiConstants;
